export const SIDEBAR_STATE_OPEN = "SIDEBAR_STATE_OPEN";
export const SIDEBAR_STATE_CLOSE = "SIDEBAR_STATE_CLOSE";
export const ENABLE_LOADER = "ENABLE_LOADER";
export const ERROR_MESSAGES = "ERROR_MESSAGES";
export const SUCCESS_MESSAGE = "SUCCESS_MESSAGE";
